# fly.toml app configuration file generated for tethys-envio-sms on 2023-12-05T22:12:42-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tethys-envio-sms"
primary_region = "gru"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
